import bcrypt                                               #bcrypt is a password security library.
import streamlit as st                                      #Streamlit is a Python library for building interactive web apps, often used for data science and dashboards.
from database import get_connection, initialize_database

# ensure the database is initialized when this module is imported
initialize_database()

def hash_password(plain_text: str) -> str:                  #Convert normal password into secure hashed password. -> str (This means the function returns a string.)
    return bcrypt.hashpw(plain_text.encode(), bcrypt.gensalt()).decode() #bcrypt.hashpw() takes the plain text password, encodes it to bytes, and hashes it using a salt generated by bcrypt.gensalt().
                                                                        #The resulting hash is then decoded back to a string for storage in the database.

def verify_password(plain_text: str, hashed: str) -> bool:              #Check whether entered password matches stored hash.-> bool True or False
    return bcrypt.checkpw(plain_text.encode(), hashed.encode())         #bcrypt.checkpw() takes the plain text password and the stored hashed password, encodes both to bytes, and checks if they match. 
                                                                        #It returns True if they match, otherwise False.

def create_default_admin():
    """Creates admin user if none exists."""                            #This is called a: docstring---It explains what the function does.
    conn = get_connection()
    cursor = conn.cursor()
    existing = cursor.execute(
        "SELECT * FROM users WHERE username = 'admin'"                  #Check if admin already exists,---- Find user whose username is admin----SELECT * Means: Get all columns
    ).fetchone()                                                        #fetchone() retrieves the first row of the result set. If no admin user exists, it returns None.

    if not existing:
        cursor.execute("""
            INSERT INTO users (username, password_hash, role)
            VALUES (?, ?, ?)
        """, ("admin", hash_password("admin123"), "admin"))             #If no admin user exists, this code inserts a new user with the username "admin", a hashed password for "admin123", and the role "admin" into the users table.
        conn.commit()
        print("✅ Default admin created: admin / admin123")
    conn.close()

def login_user(username: str, password: str):                           #This creates a function named: login_user---Check if username and password are correct.
    """Returns user dict if credentials valid, else None."""
    conn = get_connection()
    user = conn.execute(
        "SELECT * FROM users WHERE username = ?", (username,)           #Why ? is used---This is a placeholder.--- Safer than directly writing values inside SQL.
    ).fetchone()                                                        #fetchone() retrieves the first row of the result set. If no matching user is found, it returns None.
    conn.close()                                                        #Why comma is needed?("(username,))---This creates a tuple/list,---SQLite expects parameters as tuple/list.

    if user and verify_password(password, user["password_hash"]):       #Does entered password match stored hashed password?
        return dict(user)                                               #if user exists AND password correct---return dict(user)---This converts SQLite Row object into normal Python dictionary.
                                                                        #Why convert to dict?---Dictionaries are easier to use later.----{ "id": 1, "username": "admin", "role": "admin"}
    return None                                                         #If no user found or password incorrect, return None.

def show_login_page():                                                  #This creates a function named: show_login_page---Renders the streamlit login form
    """Renders the streamlit login form"""
    st. markdown("## 🔐 Login")                                         #Displays formatted text in Streamlit.---## = heading---
    st. markdown("----")                                                #This creates a separator line.--- Looks like: =====

    with st.form("login_form"):                                         #Create a form, and everything inside belongs to that form.
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")           #type="password" makes the input field hide the characters as you type, showing dots or asterisks instead of the actual characters for security.
        submit = st.form_submit_button("Login")                         #This creates a submit button for the form. When the user clicks this button, the form is submitted, and the variable 'submit' will be set to True, allowing us to check if the form was submitted and then process the login logic accordingly.
        
        if submit:
            user = login_user(username, password)                       #This line calls the login_user function with the entered username and password. If the credentials are valid, it returns a user dictionary; otherwise, it returns None.
            if user:
                st.session_state["logged_in"] = True
                st.session_state["user"] = user 
                st.session_state["role"] = user["role"]
                st.session_state["username"] = user["username"]
                st.rerun() 
            else:
                st.error("❌ Invalid username or password.")
                
def logout():
    st.session_state.clear()  # clears everything at once
    st.rerun()  
    
def require_login():
    """Call at top of every page to enforce authentication"""
    if not st.session_state.get("logged_in"):
        show_login_page()
        st.stop()
        

def require_admin():
    """Call on admin-only pages"""
    require_login()
    if st.session_state.get("role") != "admin":
        st.error("🚫 Access denied. Admins only.")
        st.stop()   